##**Thông tin**


1.   Họ tên: Trần Huỳnh Kỳ Anh
2.   MSSV: 19521216
3.   Ngày thực hiện: 02/11/2021
4.   Nội dung: 




#**Clone dữ liệu**

In [1]:
!git clone https://github.com/tranhuynhkyanh/CS116

Cloning into 'CS116'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 22 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.


#**Import thư viện và đọc dữ liệu**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold

In [3]:
dt = pd.read_csv("/content/CS116/Churn_Modelling.csv")

In [4]:
dt.head(5)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
x_data = dt.iloc[:,3:13]
x_data.head(5)

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [6]:
y_data = dt.iloc[:,13:]
y_data.head(5)

Exited
0       1
1       0
2       1
3       0
4       0

#**Bước 2+3+4**

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')

x_trans = np.array(columnTransformer.fit_transform(x_data), dtype = np.float)

In [8]:
x_trans

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [9]:
x_trans[5]

array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 6.4500000e+02, 4.4000000e+01, 8.0000000e+00,
       1.1375578e+05, 2.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       1.4975671e+05])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_trans, np.array(y_data), test_size=0.2)

In [11]:
X_train

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.7696231e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 7.3457550e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 5.8332910e+04],
       ...,
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.4633927e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 4.3018980e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.7004140e+04]])

In [12]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(x_trans)

In [ ]:
X_train

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 3.7662490e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.0538349e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.9344123e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 7.5698440e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 8.3912240e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 1.8446470e+05]])

In [ ]:
X_train.shape

(8000, 13)

#**Bước 5: Huấn luyện mô hình**

In [24]:
from keras.models import Sequential
from keras.layers import Dense
def get_model():
  model = Sequential()
  model.add(Dense(6, input_shape=(13,), activation='relu'))
  model.add(Dense(6, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [14]:
hist = model.fit(scaler.transform(X_train),y_train,epochs=100, batch_size=32)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5908 - accuracy: 0.6774
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4693 - accuracy: 0.7870
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4414 - accuracy: 0.7906
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4224 - accuracy: 0.8002
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4074 - accuracy: 0.8119
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3952 - accuracy: 0.8201
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3868 - accuracy: 0.8266
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3806 - accuracy: 0.8335
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3742 - accuracy: 0.8369
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3684 - accura

#**Bước 6: Độ chính xác**

In [ ]:
model.evaluate(scaler.transform(X_test),y_test)

63/63 [==============================] - 0s 1ms/step - loss: 0.3168 - accuracy: 0.8655


[0.3168484568595886, 0.8654999732971191]

In [33]:
hist.history['accuracy'][-1]

0.859375

In [16]:
from sklearn.metrics import confusion_matrix

In [15]:
y_pre = model.predict(scaler.transform(X_test))

In [18]:
np.around(y_pre)

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [19]:
y_test

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [20]:
confusion_matrix(y_pre.astype(int),y_test)

array([[1610,  390],
       [   0,    0]])

#**Bước 7: Test với dữ liệu**
Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

No.of Products: 2

Has credit card: Yes

Active Member: Yes

Estimated Salary: $50000


In [37]:
X_test[0]

array([0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 5.3700000e+02, 4.7000000e+01, 6.0000000e+00,
       1.0316335e+05, 1.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       1.6259640e+04])

In [39]:
data_test =[1,0,0,0,1,600,40,3,60000,2,1,1,50000]
x_dt = np.array(data_test).astype(float)
data_x = []
data_x.append(x_dt)


In [41]:
x_dt_pre = model.predict(scaler.transform(np.array(data_x)))

In [42]:
x_dt_pre[0][0]

0.02796945

In [43]:
if(int(x_dt_pre[0])):
  print("Khách hàng nên exit")
else:
  print("Khách hàng không nên exit")

Khách hàng không nên exit


#**Bước 8: Kfold = 5**

In [22]:
def kFoldSplit(X, y, k):
  kFold = KFold(n_splits=k)
  kFold.get_n_splits(X)

  list_X_train, list_y_train, list_X_test, list_y_test = [], [], [], []

  for i_train, i_test in kFold.split(X):
    list_X_train.append(X[i_train])
    list_y_train.append(y[i_train])
    list_X_test.append(X[i_test])
    list_y_test.append(y[i_test])

  return list_X_train, list_y_train, list_X_test, list_y_test


In [23]:
list_X_train, list_y_train, list_X_test, list_y_test  = kFoldSplit(scaler.transform(x_trans), np.array(y_data), 5)

In [34]:
def kfold_rslt(model):
  list_accuracy = []
  for i in range(len(list_X_train)):
    hist = model.fit(list_X_train[i], list_y_train[i],epochs=100,batch_size=32)
    list_accuracy.append(hist.history['accuracy'][-1])
  return list_accuracy


In [35]:
list_acc_score = kfold_rslt(get_model())

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7717
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4763 - accuracy: 0.7986
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4537 - accuracy: 0.8000
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4373 - accuracy: 0.8055
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4252 - accuracy: 0.8175
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4164 - accuracy: 0.8221
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4099 - accuracy: 0.8255
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4049 - accuracy: 0.8295
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4005 - accuracy: 0.8320
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3961 - accura

In [36]:
list_acc_score

[0.8650000095367432,
 0.8607500195503235,
 0.8653749823570251,
 0.8608750104904175,
 0.8647500276565552]